[theme]
primaryColor="#F39C12"
backgroundColor="#0000FF"
secondaryBackgroundColor="#F0F0F0"
textColor="#FF0000"
font="sans serif"

[server]
port = 8501
enableCORS = false

[global]
showGitHubBanner = false
