[theme]
primaryColor="#F39C12"
backgroundColor="#FFFFFF" 
secondaryBackgroundColor="#F0F0F0"
textColor="#000000"
font="sans serif"

[server]
port = 8501
enableCORS = false

[global]
showGitHubBanner = false
